FROM ubuntu:18.04
RUN apt update && apt upgrade -y
RUN apt install -y curl python3-dev python3-pip screen libxml2-dev g++ gcc
ENV PYTHONUNBUFFERED=1 PYTHONHASHSEED=random PYTHONDONTWRITEBYTECODE=1
WORKDIR /app
COPY . /app
RUN pip3 install --no-cache-dir -r requirements.txt
EXPOSE 5555
CMD ["flower", "-A", "horizon.app:app", "--broker", "amqp://rabbitmq:5672/", "--address=0.0.0.0", "--port=5555"]
