FROM python:alpine
RUN pip install --no-cache-dir redis flower requests flask
ENV PYTHONUNBUFFERED=1 PYTHONHASHSEED=random PYTHONDONTWRITEBYTECODE=1
WORKDIR /app
COPY . /app
EXPOSE 5555
USER nobody
CMD ["flower", "-A", "horizon", "--broker", "amqp://rabbitmq:5672", "--address=0.0.0.0", "--port=5555"]
