version: "3"
services:
    rabbitmq:
        hostname: rabbitmq-server
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"

    redis:
        hostname: redis-server
        image: redis:latest
        ports:
            - "6379:6379"

    flask_site:
        build: .
        command: gunicorn -b 0.0.0.0:5580 -w 4 --reload wsgi:api --chdir /app/horizon
        environment:
            PYTHONUNBUFFERED: "true"
        ports:
            - "5580:5580"
        links:
            - rabbitmq
            - redis
        healthcheck:
            test: "curl -f http://0.0.0.0:5580/index || false"
            interval: 60s
            timeout: 10s
            retries: 3

    celery_worker:
        build: .
        command: celery -A horizon.app:app worker -B -l DEBUG -c 2
        volumes:
            - .:/app
        links:
            - rabbitmq
            - redis
        depends_on:
            - rabbitmq
            - redis

    flower_monitor:
        build:
            context: .
            dockerfile: Dockerfile_flower
        command: flower -A horizon.app:app --broker=amqp://rabbitmq --address=0.0.0.0 --port=5555
        ports:
            - "5555:5555"
        depends_on:
            - rabbitmq
            - redis

    database:
        hostname: mongo
        image: mongo:latest
        ports:
            - "27017:27107"
